export const restaurants = [
  {
    id: 1,
    name: "La Pasta Mia",
    category: "Italiana",
    rating: 4.8,
    delivery: "30-40 min • Entrega grátis",
    price: "R$ 0,00",
    img: "/imagens/r1.jpg",
    banner: "/imagens/r1.jpg",
  },
  {
    id: 2,
    name: "Sushi Go",
    category: "Japonesa",
    rating: 4.7,
    delivery: "25-35 min • R$ 6,90",
    price: "R$ 6,90",
    img: "/imagens/r2.jpg",
    banner: "/imagens/r2.jpg",
  },
  {
    id: 3,
    name: "Burger House",
    category: "Lanches",
    rating: 4.6,
    delivery: "20-30 min • Entrega grátis",
    price: "R$ 0,00",
    img: "/imagens/r3.jpg",
    banner: "/imagens/r3.jpg",
  },
  {
    id: 4,
    name: "Delícia Nordestina",
    category: "Brasileira",
    rating: 4.9,
    delivery: "35-45 min • R$ 4,50",
    price: "R$ 4,50",
    img: "/imagens/r4.jpg",
    banner: "/imagens/r4.jpg",
  },
  {
    id: 5,
    name: "Veggie Life",
    category: "Vegana",
    rating: 4.5,
    delivery: "25-30 min • Entrega grátis",
    price: "R$ 0,00",
    img: "/imagens/r5.jpg",
    banner: "/imagens/r5.jpg",
  },
  {
    id: 6,
    name: "Churras Prime",
    category: "Carnes",
    rating: 4.9,
    delivery: "40-50 min • R$ 7,90",
    price: "R$ 7,90",
    img: "/imagens/r6.jpg",
    banner: "/imagens/r6.jpg",
  },
];
